# .github/workflows/aws-terraform-plan.yml

name: AWS Terraform Plan

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
      - feature/*
      - bugfix/*
      - hotfix/*


permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR
  
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
          
      - name: copy provider file
        run: |
          cp .aws_providers/dev-jnj.tf src
    

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.1

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        
      - name: select workspace
        working-directory: ./src
        run: |
          terraform workspace select dev  

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
      	working-directory: ./src
        run: terraform plan -no-color
        if: github.event_name == 'push'
        continue-on-error: true

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          echo "Terraform plan summary:"
          terraform show -json | jq '.resource_changes[] | .change.actions[]' | grep -E 'create|update|delete'

